use v6.d;

unit module Math::NIntegrate::Codes;

#| Range boundaries cases
enum RangeBoundsCases is export
<VT_FIN_FIN VT_FIN_INF VT_INF_FIN VT_INF_INF>;

#| RegionBoundaryTypes
enum RangeEndCases is export
<RE_BOTH RE_LEFT RE_RIGHT RE_ANY RE_NONE>;

#| Error codes
enum Errors is export <
ABSTRACT_CLASS_CALL
DIMENSIONS_DO_NOT_MATCH
INCORRECT_ARGUMENTS
INCORRECT_NUMERICAL_FUNCTION
INVALID_USE_OF_INF_IN_RANGE
MISSING_OBJECT
NOT_A_NUMERICAL_FUNCTION
REACHED_MAX_POINTS
REACHED_MAX_RECURSION
WRONG_TYPE
ZERO_INTERVAL
>;